### ISSUE TITLE
Number of time instants in ICEWS14

### ISSUE THREAD

**Issue by apoorvumang** [dair-iitd/tkbi#3]
![image](https://user-images.githubusercontent.com/1957903/93201980-90251000-f76f-11ea-8e81-9c43b538d240.png)

According to this, there is only 1 time instance in ICEWS14. Does this mean that link prediction is essentially time agnostic? Also isn't this too coarse, since data is from 1 year only? Maybe day-wise time instants would have been suitable here since there are only 365 separate time instances.

This makes comparison with other methods hard. (eg. https://arxiv.org/abs/1907.03143 from AAAI 2020)

Similar point for ICEWS05-15.

**Comment by sushant21** [comment]
Hi, this is a mistake, which we have fixed in an updated version of the paper (to be released soon).
We use day-wise time instants only, allowing fair comparison with existing work.

**Comment by apoorvumang** [comment]
Thanks, so the numbers in the current paper are correct?

**Comment by sushant21** [comment]
ICEWS14 improved slightly on hyper-tuning. These are the latest numbers, for your reference-
![image](https://user-images.githubusercontent.com/20418382/93206232-b26e5c00-f776-11ea-9f7c-47d563636ff7.png)

**Comment by apoorvumang** [comment]
Thank you
